# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
instance_class: F1
env: flex

automatic_scaling:
  max_num_instances: 5

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"

network:
  session_affinity: true

readiness_check:
  app_start_timeout_sec: 1800
