# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

env: flex
runtime: custom
instance_class: F2
entrypoint: java -jar /app/jars/soprafs24.jar

network:
  session_affinity: true

readiness_check:
  app_start_timeout_sec: 1800
